---
name: Deployment
on:
  push:
    branches:
      - main
      - alpha

jobs:
  release:
    name: Release
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Install Nix
        uses: cachix/install-nix-action@v14

      - name: Build Nix Dependencies
        run: |
          nix-shell shell.cd.nix --run "echo 'Successfully built nix dependencies.'"

      - name: Install Node.js dependencies
        run: |
          nix-shell shell.cd.nix --run "npm ci"

      - name: Release
        env:
          GH_TOKEN: ${{ (secrets.GROWTHAT_BOT_TOKEN || github.token) }}
          GITHUB_TOKEN: ${{ (secrets.GROWTHAT_BOT_TOKEN || github.token) }}
          GIT_AUTHOR_NAME: ${{ secrets.GROWTHAT_BOT_NAME }}
          GIT_AUTHOR_EMAIL: ${{ secrets.GROWTHAT_BOT_EMAIL }}
          GIT_COMMITTER_NAME: ${{ secrets.GROWTHAT_BOT_NAME }}
          GIT_COMMITTER_EMAIL: ${{ secrets.GROWTHAT_BOT_EMAIL }}
        run: |
          nix-shell shell.cd.nix --run "npm run release"
