---
name: Sync
on:
  release:
    types:
      - published
jobs:
  merge:
    name: Merge
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: "Merge ${{ github.ref }} -> next"
        uses: devmasx/merge-branch@1.4.0
        with:
          type: now
          target_branch: next
          github_token: ${{ github.token }}
